version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
#      MONGODB_DATABASE: appdb
#      MONGODB_USERNAME: alvaro
#      MONGODB_PASSWORD: secret
#      MONGODB_HOSTNAME: mongo
    volumes:
      - type:  bind
        source: .
        target: /web 
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INIT_DB_ROOT_USERNAME: alvaro
      MONGO_INIT_DB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    links:
      - mongo
    depends_on:
      - mongo
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: alvaro
#      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
#      ME_CONFIG_BASICAUTH_USERNAME: admin
#      ME_CONFIG_BASICAUTH_PASSWORD: secret
volumes:
  mongo-data:
