apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 31000
  type: NodePort
  selector:
    component: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template: 
    metadata:
      labels:
        component: web
    spec:
      containers:
      - name: client
        image: universidad880350/entrega_individual 
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: development
